### PR TITLE
Added delay & scramble features

### PR DESCRIPTION
**Pull request by BerkinAKKAYA**
Delay Usage

``` javascript
<Typewriter delay="1000">
	<h1>Foobar</h1>
</Typewriter>
```

Scramble Usage

``` javascript
<Typewriter mode="scramble" scrambleCount="50" interval="20">
	<h1>Foobar</h1>
</Typewriter>
```

### CODE REVIEW

**Comment by BerkinAKKAYA** [comment]
Added `scramble` feature as well as `delay`

**Comment by henriquehbr** [comment]
Hi there @BerkinAKKAYA!

First, sorry for the inconvenient, In a recent process of refactoring, i've migrated from `master` to `main`, for two reasons

- The `master` branch contained some breaking changes on `svelte-typewriter` API that should be released as either alpha, beta or release candidate beforehand, but as i'm still getting used to strictly follow semver guidelines on my projects, i ended up releasing these changes in version `v3.0.0`, and they ended up being harder to maintain and also a bit cumbersome about the excessive props to `<Typewriter>` component
- Sooner or later, newly created repositories on GitHub will have the default branch named as `main`, so i'm doing this in adaptation as well

So, if it's more convenient to you, feel free to open this PR to `main`, otherwise i can apply these changes myself

Many thanks for you time and effort contributing to `svelte-typewriter` :)

**Comment by BerkinAKKAYA** [comment]
Hi @henriquehbr, i tried to open the same PR for the `main` branch but by mistake i opened 2 requests instead and i don't know if it's possible to delete them, sorry about that 😕 I hope i correctly opened the pull request in #17. I would be happy if you applied changes if i didn't open it correctly. Thanks for your detailed explanation. Have a good day!

**Comment by henriquehbr** [comment]
Just saw your PR's, i will close #14 and keep #17 open as requested, don't worry about this, these things happen

Thanks for your contribution, have a nice day!

**Pull request closed without merging**
